### ISSUE TITLE
(from matrix) potential pretalx mail problem

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/pretalx-integration#16]
Ludovic Dubost (XWiki-CryptPad)
Hello, on the CFP system (pretalx), we tried to invite another speaker on the talk, and it seems that the invitation by mail never arrives. We looked in spam and tried multiple ways. Anybody managed to do this ?

**Comment by johanvdw** [comment]
It does work for many other people. You can always copy the invitation link and send it through another medium.

**Comment by johanvdw** [comment]
Closing it here as I don't see anything we can do about it.
