### ISSUE TITLE
The devroom CfP mail from/envelope-from is set to j******w@fosdem.org

### ISSUE THREAD

**Issue by gerryd** [FOSDEM/pretalx-integration#2]
The from/envelope-from for the devroom CfP is a staff member's personal e-mail address. Could this become devrooms@fosdem.org?

**Comment by johanvdw** [comment]
I am not sure that devrooms@ is the best one, as we will also use pretalx for main tracks/...

I've now set it to pretalx@ which forwards to devrooms@
