### ISSUE TITLE
colored time bar on fosdem website is wrong on saturday

### ISSUE THREAD

**Issue by johanvdw** [FOSDEM/pretalx-integration#41]
Eg for community devroom, which starts at 15:00 on Saturday:
![image](https://github.com/FOSDEM/pretalx-integration/assets/868434/e21472f0-76ec-433f-820b-98fee1eb0ec2)

Also on roompage: https://fosdem.org/2024/schedule/room/ua2114/
same on http://localhost:3000/2024/schedule/roomtracks/

**Comment by lucab** [comment]
I was about to report this same issue, then I saw this ticket was already opened for it.
I noticed the same bug on the Rust devroom that I'm taking care of:
![pretalx](https://github.com/FOSDEM/pretalx-integration/assets/98086/90254db1-126d-4990-9d0a-99187eb29cf5)

It should be running from 10:30 to 19:00 (Bruxelles time) but instead all the colored bars are shifted left (earlier) by 1 hour. Suspiciously, they seem to be displaying UTC time.

Row entries in the schedule table are noted with proper start/end times, though.

**Comment by cbeyls** [comment]
I didn't find any issue in the data set you provided me. Maybe an edge case in the existing code or some code changes you made recently?
It looks that the entire day is shifted 1 hour early, not just the talks: the end time should be 19:05 and is shown as 18:05.

**Comment by johanvdw** [comment]
I believe https://github.com/FOSDEM/pretalx-integration/commit/e0948d9892356c7e8576e92add4014d6d730d113 kinda fixes this.
