### ISSUE TITLE
Speaker name not properly escaped in iCal feed, resulting in failure to import

### ISSUE THREAD

**Issue by cpcallen** [FOSDEM/pretalx-integration#51]
I attempted to add `https://fosdem.org/2024/schedule/track/main_track_janson.ics` to Google Calendar both by URL and by uploading the `.ics` file to add to an existing calendar, but both failed.

- When added by URL, the resulting calendar was empty and had no title or description.  (Other FOSDEM iCal feeds I'd imported by URL were automatically given a suitable title and description, and contained events as expected.)
- When uploading the `.ics` file to add the events an existing calendar, Google calendar reported "Imported 0 out of 0 events. Unable to process your ical/CSV file."

I used an ical validation tool to inspect several of the FOSDEM iCal fees; they all contained various issues the one issue that was unique to the failing feed was:

> Property parameter values must not contain the DQUOTE (") character. near line # 260
> Reference: [3.2. Property Parameters](http://icalendar.org/iCalendar-RFC-5545/3-2-property-parameters.html)

Opening the file in a text editor, I see that line 275 contains:

    ATTENDEE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVIDUAL;CN="Fabio Alessandro "Fale" Locati":invalid:nomail

(and is part of a `VEVENT` that begins on line 260).

It appears that this FOSDEM calendar feed is therefore being corrupted by the unescaped double quotes in the speaker's nickname.

**Comment by johanvdw** [comment]
Thanks for the report. More appropriate to fix this in the website repo imho. Feel free to open other issues you encountered on the fosdem website repo.
